flowchart LR
  A[Evento: Alta 4G / Portabilidad] --> S{Segmento?}

  S -->|B2C| M{Modalidad?}
  S -->|B2B| N{Modalidad?}

  M -->|Postpago| R1[R-001 · Bolsa 10 GB]
  M -->|Híbrido|  R2[R-002 · Bolsa 10 GB]

  N -->|Postpago| R3[R-003 · Descuento mensual X%]
  N -->|Híbrido|  R4[R-004 · Bolsa 10 GB]

  R1 --> T[Trazabilidad → Reporte]
  R2 --> T
  R3 --> T
  R4 --> T

  %% Puntos de verificación
  T --> V1((CRM/BSCS))
  T --> V2((Reporte MSTR))